// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.

var findTheDifference = function(s, t) {
  let sum1 = 0;
  for (let i = 0; i < s.length; i++) {
    sum1 += s.charCodeAt(i);
  }


  let sum2 = 0;
  for (let j = 0; j < t.length; j++) {
    sum2 += t.charCodeAt(j);
  }

  return String.fromCharCode(sum2 - sum1);
};
